INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_sospecha_Colecistectomia', 1, 1);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_sospecha_Consulta o control por medico general', 1, 2);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_sospecha_Hemograma', 1, 3);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_sospecha_Perfil hepatico (funcion hepatica, incluye bilirrubina total y conjugada, fosfatasas alcalinas totales, GGT, transaminasas GOT/AST y GPT/ALT)', 1, 4);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_sospecha_Perfil bioquimico basico (incluye glucosa en sangre)', 1, 5);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_sospecha_Ecografia abdominal', 1, 6);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Consulta integral de especialidades en med. interna y subespecialidades', 7, 7);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Hemograma', 7, 3);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Perfil hepatico (funcion hepatica, incluye bilirrubina total y conjugada, fosfatasas alcalinas totales, GGT, transaminasas GOT/AST y GPT/ALT)', 7, 4);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Perfil bioquimico basico (incluye glucosa en sangre)', 7, 5);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Ecografia abdominal', 7, 6);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_TAC abdomen', 7, 8);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Colecistectomia laparascopica', 7, 9);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Biopsia Inmunohistoquimica con determinacion de CDK2, CDK7 y CK7', 7, 10);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Biopsia diferida con determinacion de Her2 e inestabilidad microstatica', 7, 11);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Visita por medico interconsultor (o en junta medica c/u) a enfermo hospitalizado', 7, 12);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Perfil hepatico', 7, 13);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Perfil renal', 7, 14);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_DHL', 7, 15);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Glucosa en sangre', 7, 16);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Albumina', 7, 17);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Perfil Bioquimica', 7, 18);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Prueba de coagulacion', 7, 19);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_ECG.de 12 derivaciones', 7, 20);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Electrolitos plasmaticos, incluye sodio, potasio, cloro)', 7, 21);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_diagnostico_Orina completa', 7, 22);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Dia cama integral de observacion o dia cama integral ambulatorio diurno', 13, 23);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Visita por medico interconsultor (o en junta medica c/u) a enfermo hospitalizado', 13, 12);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Consulta integral de sub-especialidades (en CDT)', 13, 24);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_TAC abdomen', 13, 8);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Hemograma', 13, 3);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_E.C.G. de reposo (incluye minimo 12 derivaciones y 4 complejos por derivacion)', 13, 25);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Ecocardiograma Doppler, con registro (incluye cod. 17-01-008)', 13, 26);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Ecocardiograma de estres', 13, 27);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Perfil bioquimico basico (incluye glucosa en sangre)', 13, 5);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Perfil renal (funcion renal, incluye creatinina, NUS, urea)', 13, 28);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Electrolitos plasmaticos, incluye sodio, potasio, cloro)', 13, 21);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Perfil hepatico (funcion hepatica, incluye bilirrubina total y conjugada, fosfatasas alcalinas totales, GGT, transaminasas GOT/AST y GPT/ALT)', 13, 4);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Albumina (proteinas sericas, incluye proteinas totales, albuminas)', 13, 29);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Pruebas de coagulacion (incluye tiempo de protrombina, tiempo de o consumo de (incluye INR, relacion internacional normalizada), Tromboplastina, tiempo parcial de (TTPA, TTPK o similares)', 13, 30);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_DHL', 13, 15);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Orina completa, (incluye cod. 03-09-023 y 03-09-024)', 13, 31);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Grupos sanguineos ABO y RhO (incluye estudio de factor Du en Rh negativos)', 13, 32);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Prueba de compatibilidad por unidad de globulos rojos (proc. aut.)', 13, 33);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Coombs indirecto', 13, 34);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Set de examenes por unidad de globulos rojos transfundida (incluye clasificacion ABO y RHO, VDRL, HIV, virus hepatitis B, antigeno de superficie, anticuerpos de hepatitis C, HTLV - I y II, Chagas, prueba de compatibi', 13, 35);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Antigeno CA19-9', 13, 36);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_PET', 13, 37);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Cirugia de abdomen y pelvis', 13, 38);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Instalacion de cateter para quimioterapia', 13, 39);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Radiografia de torax frontal y lateral', 13, 40);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Consulta integral de especialidades en medicina interna y subespecialidades, oftalmologia, neurologia, oncologia', 13, 41);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Consulta o control por enfermera, matrona, kinesiologa o nutricionista', 13, 42);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Consulta o control por psicologo clinico', 13, 43);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Protesis biliar endoscopica', 13, 44);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Derivacion biliodigestiva', 13, 45);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Cuna hepatica', 13, 46);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Cirugia radical oncologica', 13, 47);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Cateter PIC', 13, 48);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Cateter con reservorio', 13, 49);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Drenaje Percutaneo', 13, 50);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Curacion simple ambulatoria', 13, 51);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Dia cama hospitalizacion integral adulto en unidad de cuidado intensivo (U.C.I.)', 13, 52);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Dia cama hospitalizacion integral adulto en unidad de tratamiento intermedio (U.T.I.)', 13, 53);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Dia cama hospitalizacion integral medicina, cirugia, obstetricia-ginecologia y especialidades (sala 3 camas o mas) (hospital alta complejidad)', 13, 54);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Estudio histopatologico: Biopsia con deteccion de Antigeno CA19-9', 13, 55);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Resonancia Magnetica Nuclear de abdomen', 13, 56);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Tomografia computarizada de abdomen (higado, vias y vesicula biliar, pancreas, bazo, suprarrenales y rinones)', 13, 57);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Tomografia computarizada de pelvis (ademas incluye sacro, coxis, caderas, huesos pelvicos, articulaciones sacro iliacas). Bilateral', 13, 58);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Panel genetico para biomarcadores', 13, 59);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Quimioterapia', 13, 60);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Radioterapia', 13, 61);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_tratamiento_Radioquimioterapia', 13, 62);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_seguimiento_Consulta integral de especialidades en cirugia, ginecologia y obstetricia, ortopedia y traumatologia (en CDT)', 19, 63);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_seguimiento_Consulta o control por psicologo clinico', 19, 43);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_seguimiento_TAC TAP', 19, 64);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_seguimiento_Hemograma (incluye recuentos de leucocitos y eritrocitos, hemoglobina, hematocrito, formula leucocitaria, caracteristicas de los elementos figurados y velocidad de eritrosedimentacion)', 19, 65);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_seguimiento_Perfil hepatico (funcion hepatica, incluye bilirrubina total y conjugada, fosfatasas alcalinas totales, GGT, transaminasas GOT/AST y GPT/ALT)', 19, 4);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_seguimiento_Antigeno CA19-9', 19, 36);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_seguimiento_PET', 19, 37);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_seguimiento_Resonancia Magnetica Nuclear de abdomen', 19, 56);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_seguimiento_Panel genetico para biomarcadores', 19, 59);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Capacitacion y apoyo para cuidadores y familias', 25, 66);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Consejeria educacional, entrenamiento y soporte', 25, 67);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Consejeria vocacional, entrenamiento y soporte', 25, 68);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Educacion, asesoramiento y apoyo para un estilo de vida saludable y la autogestion de la condicion de salud', 25, 69);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Ejercicios de fortalecimiento muscular', 25, 70);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Ejercicios de piso pelvico', 25, 71);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Ejercicios de rango de movimiento', 25, 72);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Ejercicios de relajacion', 25, 73);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Entrenamiento actividades de la vida diaria', 25, 74);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Entrenamiento cognitivo', 25, 75);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Entrenamiento del equilibrio', 25, 76);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Entrenamiento fisico', 25, 77);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Entrenamiento movilidad', 25, 78);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Estimulacion nerviosa electrica transcutanea (TENS)', 25, 79);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Intervenciones centradas en la participacion', 25, 80);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Modificacion de ambiente del hogar', 25, 81);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Provision y capacitacion en el uso de herramientas de apoyo para la movilidad', 25, 82);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Provision y capacitacion en el uso de productos de asistencia para el autocuidado', 25, 83);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Tecnicas de tejidos blandos', 25, 84);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Terapia descongestiva completa', 25, 85);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Terapia psicologica', 25, 86);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_rehabilitacion_Termoterapia', 25, 87);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_paliativo_Dia cama integral de observacion o dia cama integral ambulatorio diurno', 31, 23);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_paliativo_Instalacion de cateter para quimioterapia', 31, 39);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_paliativo_Radioterapia', 31, 61);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_paliativo_Radioquimioterapia', 31, 62);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_vesicula_paliativo_Drenaje via biliar', 31, 88);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Consulta integral de especialidades en medicina interna y subespecialidades, oftalmologia, neurologia, oncologia (hosp. alta complejidad)', 9, 159);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Perfil hepatico (incluye tiempo de protrombina, bilirrubina total y conjugada, fosfatasas alcalinas totales, GGT, transaminasas GOT/AST y GPT/ALT)', 9, 160);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Perfil bioquimico (determinacion automatizada de 12 parametros)', 9, 161);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Hemograma (incluye recuentos de leucocitos y eritrocitos, hemoglobina, hematocrito, formula leucocitaria, caracteristicas de los elementos figurados y velocidad de eritrosedimentacion)', 9, 65);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Perfil renal (funcion renal incluye creatinina NUS urea)', 9, 109);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Albumina (proteinas sericas incluye proteinas totales albuminas)', 9, 112);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Dlco (capacidad de difusion del monoxido de carbono)', 9, 162);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Tomografia computarizada de pelvis (ademas incluye sacro coxis caderas huesos pelvicos articulaciones sacro iliacas). Bilateral', 9, 118);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Cintigrama oseo', 9, 163);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Radiografia de torax frontal y lateral', 9, 40);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Tomografia computarizada de torax total', 9, 164);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Tomografia computarizada de abdomen (higado, vias y vesicula biliar, pancreas, bazo, suprarrenales y rinones)', 9, 57);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Creatinina', 9, 105);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Tiempo de protrombina (incluye INR, razon internacional normalizada)', 9, 165);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Tromboplastina (TTPA, TTPK o similares)', 9, 166);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Electrolitos plasmaticos (sodio, potasio, cloro) c/u', 9, 136);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Recuento de plaquetas (absoluto)', 9, 167);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Espirometria basal (con o sin broncodilatador)', 9, 168);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Test de marcha o caminata de 6 minutos', 9, 169);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Cintigrafia osea trifasica (incluye mediciones fase precoz y tardia)', 9, 170);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Gases y equilibrio acido base en sangre (incluye: pH, O2, CO2,exceso de base y bicarbonato), todos o cada uno de los parametros', 9, 171);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Puncion percutanea', 9, 172);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Estudio histopatologico con tecnicas histoquimicas especiales', 9, 94);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Estudio histopatologico corriente de biopsia diferida', 9, 122);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Estudio histopatologico con tecnicas de inmunohistoquimica o inmunofluorescencia (por cada organo)', 9, 96);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Estudio histopatologico con con tincion corriente de biopsia diferida con estudio seriado', 9, 97);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Estudio histopatologico de biopsia contemporanea (rapida) a intervenciones quirurgicas (por cada organo) (no incluye biopsia diferida)', 9, 98);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Estudios moleculares especificos', 9, 99);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Nasofaringolaringofibroscopia', 9, 173);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Biopsia pulmonar (con aguja) no incluye la radiologia', 9, 174);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Consulta integral de especialidades en cirugia, ginecologia y obstetricia, ortopedia y traumatologia (hosp. alta complejidad)', 9, 175);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Videotoracoscopia', 9, 176);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Pleurotomia unica o doble c/s biopsia con trocar', 9, 177);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Toracotomia minima c/s reseccion costal, c/s biopsia, c/s drenaje', 9, 178);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Citologia aspirativa (por puncion); por cada organo', 9, 179);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Tomografia computarizada de craneo encefalica', 9, 180);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Resonancia magnetica craneo encefalica', 9, 181);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Pet-ct', 9, 182);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Mediastinotomia exploradora ant.o post.c/s biopsia proc.aut', 9, 183);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_diagnostico_Visita por medico interconsultor (o en junta medica c/u) a enfermo hospitalizado', 9, 12);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Radiografia de torax frontal y lateral', 15, 40);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Pet-ct', 15, 182);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Orina completa', 15, 22);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Perfil hepatico (incluye tiempo de protrombina, bilirrubina total y conjugada, fosfatasas alcalinas totales, GGT, transaminasas GOT/AST y GPT/ALT)', 15, 160);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Perfil bioquimico (determinacion automatizada de 12 parametros)', 15, 161);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Clasificacion sanguinea ABO y RH0', 15, 184);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Hematocrito', 15, 185);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Hemograma (incluye recuentos de leucocitos y eritrocitos, hemoglobina, hematocrito, formula leucocitaria, caracteristicas de los elementos figurados y velocidad de eritrosedimentacion)', 15, 65);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Dlco (capacidad de difusion del monoxido de carbono)', 15, 162);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Tiempo de protrombina (incluye INR, razon internacional normalizada)', 15, 165);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Tiempo parcial de Tromboplastina, (TTPA, TTPK o similares)', 15, 186);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Glucosa', 15, 104);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_E.C.G. de reposo (incluye minimo 12 derivaciones y 4 complejos por derivacion)', 15, 25);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Ecocardiograma doppler, con registro (incluye cod. 17-01- 008)', 15, 187);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Ecocardiograma de estres', 15, 27);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Mediastinotomia exploradora ant.o post.c/s biopsia proc.aut', 15, 183);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Estudio histopatologico con tecnicas histoquimicas especiales', 15, 94);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Estudio histopatologico corriente de biopsia diferida', 15, 122);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Estudio histopatologico con tecnicas de inmunohistoquimica o inmunofluorescencia (por cada organo)', 15, 96);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Estudio histopatologico con con tincion corriente de biopsia diferida con estudio seriado', 15, 97);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Estudio histopatologico de biopsia contemporanea (rapida) a intervenciones quirurgicas (por cada organo) (no incluye biopsia diferida)', 15, 98);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Estudios moleculares especificos', 15, 99);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Toracotomia exploradora, c/s biopsia, c/s debridacion, c/s drenaje', 15, 188);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Plastia de traquea y/o bronquios c/s reseccion, c/s protesis (no incluye el valor de la protesis)', 15, 189);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Pleurodesis por toracotomia', 15, 190);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Neumonectomia c/s reseccion de pared costal', 15, 191);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Reseccion metastasis unilateral', 15, 192);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Reseccion metastasis bilateral, trat. quir. por esternotomia', 15, 193);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Pleurotomia unica o doble c/s biopsia con trocar', 15, 177);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Lobectomia o bilobectomia', 15, 194);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Laringotraqueoscopia con tubo rigido', 15, 195);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Extirpacion tumores traqueales', 15, 196);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Reseccion de costillas y/o pared costal y/o cartilago y/o esternon s/plastia (proc. aut.)', 15, 197);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Mediastinoscopia c/s biopsia', 15, 198);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Protesis para plastia de traquea y/o bronquios c/s reseccion', 15, 199);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Resecciones segmentarias', 15, 200);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Dia cama hospitalizacion integral medicina, cirugia, pediatria, obstetricia-ginecologia y especialidades (sala 3 camas o mas) (hosp. alta complejidad)', 15, 201);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Dia cama hospitalizacion integral adulto en unidad de cuidado intensivo (u.c.i.)', 15, 52);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Dia cama hospitalizacion integral adulto en unidad de tratamiento intermedio (u.t.i)', 15, 202);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Atencion kinesiologica integral', 15, 203);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Consulta o control por enfermera, matrona o nutricionista', 15, 125);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Tomografia axial computarizada para planificacion radioterapia (preguntar por tratamiento con linac Dual o Tratamiento con Linac Monoenergetico)', 15, 204);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Radioterapia con LINAC DUAL (estandar, Compleja, Altamente Compleja, Convencional)', 15, 205);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Radioterapia con LINAC Monoenergetico (estandar, Compleja, Altamente Compleja, Convencional)', 15, 206);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Radioterapia', 15, 61);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Quimioterapia', 15, 60);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Consulta integral de especialidades en cirugia, ginecologia y obstetricia, ortopedia y traumatologia (hosp. alta complejidad)', 15, 175);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_tratamiento_Visita por medico interconsultor (o en junta medica c/u) a enfermo hospitalizado', 15, 12);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_seguimiento_Consulta integral de especialidades en cirugia, ginecologia y obstetricia, ortopedia y traumatologia (hosp. alta complejidad)', 21, 175);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_seguimiento_Tomografia computarizada de torax total', 21, 164);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_seguimiento_Pet-ct', 21, 182);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Capacitacion y apoyo para cuidadores y familias', 27, 66);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Consejeria educacional, entrenamiento y soporte', 27, 67);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Consejeria vocacional, entrenamiento y soporte', 27, 68);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Educacion, asesoramiento y apoyo para un estilo de vida saludable y la autogestion de la condicion de salud', 27, 69);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Ejercicios de fortalecimiento muscular', 27, 70);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Ejercicios de piso pelvico', 27, 71);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Ejercicios de rango de movimiento', 27, 72);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Ejercicios de relajacion', 27, 73);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Entrenamiento actividades de la vida diaria', 27, 74);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Entrenamiento cognitivo', 27, 75);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Entrenamiento del equilibrio', 27, 76);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Entrenamiento fisico', 27, 77);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Entrenamiento movilidad', 27, 78);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Estimulacion nerviosa electrica transcutanea (TENS)', 27, 79);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Intervenciones centradas en la participacion', 27, 80);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Modificacion de ambiente del hogar', 27, 81);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Provision y capacitacion en el uso de herramientas de apoyo para la movilidad', 27, 82);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Provision y capacitacion en el uso de productos de asistencia para el autocuidado', 27, 83);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Tecnicas de tejidos blandos', 27, 84);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Terapia descongestiva completa', 27, 85);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Terapia psicologica', 27, 86);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_pulmon_rehabilitacion_Termoterapia', 27, 87);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Consulta integral de especialidades en cirugia, ginecologia y obstetricia, ortopedia y traumatologia (en cdt)', 10, 63);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Perfil bioquimico (determinacion automatizada de 12 parametros)', 10, 161);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Perfil renal', 10, 14);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Perfil hepatico (incluye tiempo de protrombina, bilirrubina total y conjugada, fosfatasas alcalinas totales, ggt, transaminasas got/ast y gpt/alt)', 10, 160);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Hematocrito (proc. aut.)', 10, 207);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Hemograma (incluye recuentos de leucocitos y eritrocitos, hemoglobina, hematocrito, formula leucocitaria, caracteristicas de los elementos figurados y velocidad de eritrosedimentacion)', 10, 65);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Tiempo de protrombina (incluye inr, razon internacional normalizada)', 10, 165);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Deshidrogenasa lactica total (ldh)', 10, 113);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Glucosa', 10, 104);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Proteinas totales o albuminas, c/u', 10, 208);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Dia cama integral de observacion o dia cama integral ambulatorio diurno', 10, 23);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Colonoscopia larga (incluye sigmoidoscopia y colonoscopia izquierda)', 10, 210);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Estudio histopatologico con tecnicas histoquimicas especiales', 10, 94);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Estudio histopatologico corriente de biopsia diferida', 10, 122);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Estudio histopatologico con tecnicas de inmunohistoquimica o inmunofluorescencia (por cada organo)', 10, 96);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Estudio histopatologico con con tincion corriente de biopsia diferida con estudio seriado', 10, 97);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Estudio histopatologico de biopsia contemporanea (rapida) a intervenciones quirurgicas (por cada organo) (no incluye biopsia diferida)', 10, 98);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Estudios moleculares especificos', 10, 99);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Polipo rectal, trat.quir. por via anal', 10, 211);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Tiempo de Coagulacion', 10, 212);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Clasificacion sanguinea ab0 y rhd', 10, 213);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Tromboplastina, tiempo parcial de (ttpa, ttpk o similares)', 10, 214);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Creatinina', 10, 105);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Electrolitos plasmaticos', 10, 215);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Nitrogeno ureico y/o urea', 10, 216);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Orina completa, (incluye cod. 03-09-023 y 03-09-024)', 10, 31);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Antigeno carcinoembrionario (cea)', 10, 217);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Antigeno ca 125, ca 15-3 y ca 19-9, c/u', 10, 218);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_radiografia de torax frontal y lateral', 10, 40);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Tomografia computarizada de torax total', 10, 164);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Tomografia computarizada de abdomen (higado, vias y vesicula biliar, pancreas, bazo, suprarrenales y rinones)', 10, 57);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Tomografia computarizada de pelvis', 10, 219);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Ecografia abdominal (incluye higado, via biliar, vesicula, pancreas, rinones, bazo, retroperitoneo y grandes vasos)', 10, 220);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_E.c.g. de reposo (incluye minimo 12 derivaciones y 4 complejos por derivacion)', 10, 25);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Dia cama hospitalizacion integral medicina, cirugia, pediatria, obstetricia-ginecologia y especialidades (sala 3 camas o mas) (hosp. alta complejidad)', 10, 201);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Puncion de liquido ascitico, diagnostica', 10, 221);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Cistoscopia y/o uretrocistoscopia y/o uretroscopia (proc.aut.)', 10, 222);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Urocultivo, recuento de colonias y antibiograma (cualquier tecnica) (incluye toma de orina aseptica y frasco recolector) (no incluye recolector pediatrico ni sonda)', 10, 223);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Biopsia quirurgica rectal (proc. aut.)', 10, 224);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_diagnostico_Visita por medico interconsultor (o en junta medica c/u) a enfermo hospitalizado', 10, 12);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Visita por medico interconsultor (o en junta medica c/u) a enfermo hospitalizado', 16, 12);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Hematocrito (proc. aut.)', 16, 207);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Hemograma (incluye recuentos de leucocitos y eritrocitos, hemoglobina, hematocrito, formula leucocitaria, caracteristicas de los elementos figurados y velocidad de eritrosedimentacion)', 16, 65);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Creatinina', 16, 105);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Electrolitos plasmaticos (sodio, potasio, cloro) c/u', 16, 136);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Glucosa', 16, 104);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Nitrogeno ureico y/o urea', 16, 216);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Proteinas totales o albuminas, c/u', 16, 208);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Antigeno ca 125, ca 15-3 y ca 19-9, c/u', 16, 218);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Orina completa, (incluye cod. 03-09-023 y 03-09-024)', 16, 31);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Urocultivo, recuento de colonias y antibiograma (cualquier tecnica) (incluye toma de orina aseptica y frasco recolector) (no incluye recolector pediatrico ni sonda)', 16, 223);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Radiografia de torax frontal y lateral', 16, 40);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Tomografia computarizada de torax total', 16, 164);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Tomografia computarizada de abdomen (higado, vias y vesicula biliar, pancreas, bazo, suprarrenales y rinones)', 16, 57);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Tomografia computarizada de pelvis', 16, 219);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Ecografia abdominal (incluye higado, via biliar, vesicula, pancreas, rinones, bazo, retroperitoneo y grandes vasos)', 16, 220);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Resonancia magnetica de abdomen y pelvis', 16, 225);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Ecocardiograma doppler', 16, 226);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Ecocardiograma de estres', 16, 27);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_E.c.g. de reposo (incluye minimo 12 derivaciones y 4 complejos por derivacion)', 16, 25);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Antigeno carcinoembrionario (cea)', 16, 217);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Prueba de Coombs indirecto', 16, 227);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Isoinmunizacion, deteccion de anticuerpos irregulares (proc. aut.).', 16, 228);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Tromboplastina, tiempo parcial de (ttpa, ttpk o similares)', 16, 214);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Preparacion de globulos rojos, plasma, plaquetas o crioprecipitados (incluye entrevista, seleccion del donante y la preparacion del respectivo hemocomponente)', 16, 229);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Set de examenes por unidad de globulos rojos transfundida (incluye clasificacion abo y rho, vdrl, hiv, virus hepatitis b antigeno de superficie, anticuerpos de hepatitis c, htlv - i y ii, chagas, prueba de compatibilida', 16, 137);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Clasificacion sanguinea ab0 y rhd', 16, 213);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Prueba de compatibilidad por unidad de globulos rojos estudiada (proc. aut.)', 16, 230);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Dia cama integral de observacion o dia cama integral ambulatorio diurno', 16, 23);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Colonoscopia larga (incluye sigmoidoscopia y colonoscopia izquierda)', 16, 210);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Estudio histopatologico con tecnicas histoquimicas especiales', 16, 94);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Estudio histopatologico corriente de biopsia diferida', 16, 122);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Estudio histopatologico con tecnicas de inmunohistoquimica o inmunofluorescencia (por cada organo)', 16, 96);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Estudio histopatologico con con tincion corriente de biopsia diferida con estudio seriado', 16, 97);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Estudio histopatologico de biopsia contemporanea (rapida) a intervenciones quirurgicas (por cada organo) (no incluye biopsia diferida)', 16, 98);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Estudios moleculares especificos', 16, 99);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Puncion de liquido ascitico, diagnostica', 16, 221);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Polipo rectal, trat.quir. por via anal', 16, 211);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Cistoscopia y/o uretrocistoscopia y/o uretroscopia (proc.aut.)', 16, 222);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Dia cama hospitalizacion integral medicina, cirugia, pediatria, obstetricia-ginecologia y especialidades (sala 3 camas o mas) (hosp. alta complejidad)', 16, 201);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Dia cama hospitalizacion integral adulto en unidad de cuidado intensivo (u.c.i.)', 16, 52);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Dia cama hospitalizacion integral adulto en unidad de tratamiento intermedio (u.t.i)', 16, 202);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Transfusion en adulto o nino en pabellon (con asistencia permanente del medico o tecnologo medico responsable) (no corresponde su cobro cuando sea controlada por medico anestesista, por estar incluida en el valor de sus', 16, 231);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Tumor y/o quiste peritoneal (parietal)', 16, 232);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Tumor y/o quiste retroperitoneal', 16, 233);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Hepatectomia segmentaria (proc. aut.)', 16, 234);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Lobectomia hepatica (proc. aut.)', 16, 235);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Colectomia total abdominal', 16, 237);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Operacion de Hartmann  (o similar)', 16, 238);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Reseccion abdomino-perineal de ano y recto (2 equipos)', 16, 239);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Reseccion abdomino-perineal de ano y recto ampliada (2 equipos) (incluye genitales femeninos)', 16, 240);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Reseccion anterior de recto', 16, 241);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Colectomia parcial o hemicolectomia laparoscopica', 16, 242);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Educacion de grupo por enfermera, matrona o nutricionista', 16, 146);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Consulta o control por psicologo clinico', 16, 43);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Reconstitucion transito post operacion de hartmann o sim.', 16, 243);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Cierre de colostomia (proc. aut.)', 16, 244);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Consulta integral de especialidades en medicina interna y subespecialidades, oftalmologia, neurologia, oncologia (hosp. alta complejidad)', 16, 159);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Curacion simple ambulatoria', 16, 51);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Deshidrogenasa lactica total (ldh)', 16, 113);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Perfil bioquimico (determinacion automatizada de 12 parametros)', 16, 161);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Instalacion de cateter swan-ganz o similar, en adultos o ninos (proc. aut.)', 16, 148);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Consulta o control por enfermera, matrona o nutricionista', 16, 125);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Instalacion de cateter para quimioterapia', 16, 39);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Quimioterapia', 16, 60);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Consulta integral de especialidades en medicina interna y subespecialidades, oftalmologia, neurologia, oncologia (en cdt)', 16, 245);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_tratamiento_Radioterapia (acelerador de electrones)', 16, 246);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Consulta integral de especialidades en cirugia, ginecologia y obstetricia, ortopedia y traumatologia (en cdt)', 22, 63);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Educacion de grupo por enfermera, matrona o nutricionista', 22, 146);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Hemograma (incluye recuentos de leucocitos y eritrocitos, hemoglobina, hematocrito, formula leucocitaria, caracteristicas de los elementos figurados y velocidad de eritrosedimentacion)', 22, 65);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Perfil bioquimico (determinacion automatizada de 12 parametros)', 22, 161);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Perfil hepatico (incluye tiempo de protrombina, bilirrubina total y conjugada, fosfatasas alcalinas totales, ggt, transaminasas got/ast y gpt/alt)', 22, 160);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Nitrogeno ureico y/o urea', 22, 216);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Creatinina', 22, 105);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Electrolitos plasmaticos (sodio, potasio, cloro) c/u', 22, 136);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Antigeno ca 125, ca 15-3 y ca 19-9, c/u', 22, 218);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Antigeno carcinoembrionario (cea)', 22, 217);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Tomografia computarizada de abdomen (higado, vias y vesicula biliar, pancreas, bazo, suprarrenales y rinones)', 22, 57);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Tomografia computarizada de pelvis', 22, 219);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Tomografia computarizada de torax total', 22, 164);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Resonancia magnetica de abdomen y pelvis', 22, 225);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Ecografia abdominal (incluye higado, via biliar, vesicula, pancreas, rinones, bazo, retroperitoneo y grandes vasos)', 22, 220);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Consulta o control por psicologo clinico', 22, 43);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Colonoscopia larga (incluye sigmoidoscopia y colonoscopia izquierda)', 22, 210);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Estudio histopatologico con tecnicas histoquimicas especiales', 22, 94);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Estudio histopatologico corriente de biopsia diferida', 22, 122);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Estudio histopatologico con tecnicas de inmunohistoquimica o inmunofluorescencia (por cada organo)', 22, 96);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Estudio histopatologico con con tincion corriente de biopsia diferida con estudio seriado', 22, 97);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Estudio histopatologico de biopsia contemporanea (rapida) a intervenciones quirurgicas (por cada organo) (no incluye biopsia diferida)', 22, 98);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_seguimiento_Estudios moleculares especificos', 22, 99);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Capacitacion y apoyo para cuidadores y familias', 28, 66);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Consejeria educacional, entrenamiento y soporte', 28, 67);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Consejeria vocacional, entrenamiento y soporte', 28, 68);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Educacion, asesoramiento y apoyo para un estilo de vida saludable y la autogestion de la condicion de salud', 28, 69);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Ejercicios de fortalecimiento muscular', 28, 70);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Ejercicios de piso pelvico', 28, 71);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Ejercicios de rango de movimiento', 28, 72);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Ejercicios de relajacion', 28, 73);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Entrenamiento actividades de la vida diaria', 28, 74);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Entrenamiento cognitivo', 28, 75);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Entrenamiento del equilibrio', 28, 76);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Entrenamiento fisico', 28, 77);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Entrenamiento movilidad', 28, 78);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Estimulacion nerviosa electrica transcutanea (TENS)', 28, 79);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Intervenciones centradas en la participacion', 28, 80);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Modificacion de ambiente del hogar', 28, 81);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Provision y capacitacion en el uso de herramientas de apoyo para la movilidad', 28, 82);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Provision y capacitacion en el uso de productos de asistencia para el autocuidado', 28, 83);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Tecnicas de tejidos blandos', 28, 84);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Terapia descongestiva completa', 28, 85);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Terapia psicologica', 28, 86);
INSERT INTO tc_FormularioBase (nombre, etapa_patologia_id, prestacion_id) VALUES ('Formulario cancer_colon_rehabilitacion_Termoterapia', 28, 87);
