INSERT INTO tc_Pregunta (id, texto) VALUES (1, '¿Se le indico esta prestacion?');
INSERT INTO tc_Pregunta (id, texto) VALUES (2, 'Indique la fecha en que se le indico esta prestacion');
INSERT INTO tc_Pregunta (id, texto) VALUES (3, '¿Se realizo esta prestacion?');
INSERT INTO tc_Pregunta (id, texto) VALUES (4, '¿Donde se realizo esta prestacion?');
INSERT INTO tc_Pregunta (id, texto) VALUES (5, 'Indique la fecha en que se le realizo esta prestacion');
INSERT INTO tc_Pregunta (id, texto) VALUES (6, '¿Fue el motivo de esta cirugia la sospecha de cancer?');
INSERT INTO tc_Pregunta (id, texto) VALUES (7, 'Indique que tipo de cirugia se realizo?');
INSERT INTO tc_Pregunta (id, texto) VALUES (8, 'Ante la ausencia de sospecha de cancer, indique que tipo de cirugia se realizo');
INSERT INTO tc_Pregunta (id, texto) VALUES (9, 'Si la cirugia se hizo sin sospecha de cancer,?Existia evidencia de sintomas: dolor y baja de peso?');
INSERT INTO tc_Pregunta (id, texto) VALUES (10, 'Revisar en sistema si existen reagendamientos. ?Se reagendo esta prestacion?');
INSERT INTO tc_Pregunta (id, texto) VALUES (11, '¿Cuantas veces se reagendo esta prestacion?');
INSERT INTO tc_Pregunta (id, texto) VALUES (12, 'Fecha de primer reagendamiento');
INSERT INTO tc_Pregunta (id, texto) VALUES (13, '¿Por que se reagendo esta prestacion?');
INSERT INTO tc_Pregunta (id, texto) VALUES (14, 'Fecha de segundo reagendamiento');
INSERT INTO tc_Pregunta (id, texto) VALUES (15, '¿Por que se reagendo por segunda vez esta prestacion?');
INSERT INTO tc_Pregunta (id, texto) VALUES (16, 'Fecha de tercer reagendamiento');
INSERT INTO tc_Pregunta (id, texto) VALUES (17, '¿Por que se reagendo por tercera vez esta prestacion?');
INSERT INTO tc_Pregunta (id, texto) VALUES (18, 'Fecha de cuarto reagendamiento');
INSERT INTO tc_Pregunta (id, texto) VALUES (19, '¿Por que se reagendo por cuarta vez esta prestacion?');
INSERT INTO tc_Pregunta (id, texto) VALUES (20, 'Fecha de quinto reagendamiento');
INSERT INTO tc_Pregunta (id, texto) VALUES (21, '¿Por que se reagendo por quinta vez esta prestacion?');
INSERT INTO tc_Pregunta (id, texto) VALUES (22, '¿Se le informo el resultado de este examen?');
INSERT INTO tc_Pregunta (id, texto) VALUES (23, 'Indique la fecha en que se le informo el resultado de este examen');
INSERT INTO tc_Pregunta (id, texto) VALUES (24, 'Indique la fecha en que se le realizo la prestacion siguiente al informe de resultados del examen');
INSERT INTO tc_Pregunta (id, texto) VALUES (25, 'Indique que especialista lo atendio');
INSERT INTO tc_Pregunta (id, texto) VALUES (26, '¿Se le informo el resultado de la junta medica oncologica?');
INSERT INTO tc_Pregunta (id, texto) VALUES (27, 'Indique la fecha en que se le informo el resultado de esta prestacion');
INSERT INTO tc_Pregunta (id, texto) VALUES (28, 'Indique la fecha en que se le realizo la prestacion siguiente al informe de resultados de la prestacion');
INSERT INTO tc_Pregunta (id, texto) VALUES (29, 'Etapificacion cancer de vesicula');
INSERT INTO tc_Pregunta (id, texto) VALUES (30, 'Indique la fecha en que se le realizo la prestacion siguiente al informe de resultados de esta prestacion');
INSERT INTO tc_Pregunta (id, texto) VALUES (31, 'Indique la fecha de alta hospitalaria');
INSERT INTO tc_Pregunta (id, texto) VALUES (32, 'Indique el o los diagnosticos de alta hospitalaria (ver GRD del episodio)');
INSERT INTO tc_Pregunta (id, texto) VALUES (33, 'Indique la fecha en que se le informo el resultado de la junta medica');
INSERT INTO tc_Pregunta (id, texto) VALUES (34, '¿Se realizo biopsia?');
INSERT INTO tc_Pregunta (id, texto) VALUES (35, 'Indique la fecha en que se le realizo la prestacion siguiente a este procedimiento');
INSERT INTO tc_Pregunta (id, texto) VALUES (36, 'Indique que tipo de cateter fue indicado');
INSERT INTO tc_Pregunta (id, texto) VALUES (37, 'Indique que tipo de cateter fue instalado');
INSERT INTO tc_Pregunta (id, texto) VALUES (38, '¿El cateter quedo operativo?');
INSERT INTO tc_Pregunta (id, texto) VALUES (39, '¿Que tipo de estudio de biopsia se le indico?');
INSERT INTO tc_Pregunta (id, texto) VALUES (40, '¿Se le informo el resultado de la biopsia?');
INSERT INTO tc_Pregunta (id, texto) VALUES (41, 'Indique la fecha en que se le informo el resultado de la biopsia');
INSERT INTO tc_Pregunta (id, texto) VALUES (42, '¿Que tipo de quimioterapia se le indico?');
INSERT INTO tc_Pregunta (id, texto) VALUES (43, 'En cuanto a las drogas usadas en tratamiento ?Que drogas se le indico?');
INSERT INTO tc_Pregunta (id, texto) VALUES (44, 'Otra droga');
INSERT INTO tc_Pregunta (id, texto) VALUES (45, '¿De que linea de tratamiento fueron las drogas referidas?');
INSERT INTO tc_Pregunta (id, texto) VALUES (46, 'Indique numero de ciclos en plan de tratamiento');
INSERT INTO tc_Pregunta (id, texto) VALUES (47, 'Indique numero de ciclos efectivamente realizadas');
INSERT INTO tc_Pregunta (id, texto) VALUES (48, 'Indique la fecha de inicio del tratamiento');
INSERT INTO tc_Pregunta (id, texto) VALUES (49, 'Indique la fecha de termino del tratamiento');
INSERT INTO tc_Pregunta (id, texto) VALUES (50, 'Indique la fecha en que se le indico la prestacion siguiente a este procedimiento');
INSERT INTO tc_Pregunta (id, texto) VALUES (51, '¿Hubo alguna interrupcion en el tratamiento?');
INSERT INTO tc_Pregunta (id, texto) VALUES (52, 'Por que se interrumpio el tratamiento?');
INSERT INTO tc_Pregunta (id, texto) VALUES (53, '¿Que tipo de radioterapia se le indico?');
INSERT INTO tc_Pregunta (id, texto) VALUES (54, '¿Que tipo de Radioquimioterapia se le indico?');
INSERT INTO tc_Pregunta (id, texto) VALUES (55, 'Indique que tipo de especialista lo atendio');
INSERT INTO tc_Pregunta (id, texto) VALUES (56, 'Otro especialista');
INSERT INTO tc_Pregunta (id, texto) VALUES (57, '¿Que profesion tiene la persona que realiza la atencion/prestacion?');
INSERT INTO tc_Pregunta (id, texto) VALUES (58, 'Otra profesion');
INSERT INTO tc_Pregunta (id, texto) VALUES (59, 'Indque la fecha de inicio de la terapia');
INSERT INTO tc_Pregunta (id, texto) VALUES (60, 'Indique la fecha de termino de la terapia');
INSERT INTO tc_Pregunta (id, texto) VALUES (61, 'Indique el numero de sesiones realizadas');
INSERT INTO tc_Pregunta (id, texto) VALUES (62, 'Inidque la fecha de inicio del tratamiento');
INSERT INTO tc_Pregunta (id, texto) VALUES (63, '¿Por que se interrumpio el tratamiento?');
INSERT INTO tc_Pregunta (id, texto) VALUES (64, '¿En cual establecimiento de la Red SSMSO?');
INSERT INTO tc_Pregunta (id, texto) VALUES (65, 'Indique que medico especialista lo atendio');
INSERT INTO tc_Pregunta (id, texto) VALUES (66, '¿Cual otro medico especialista?');
INSERT INTO tc_Pregunta (id, texto) VALUES (67, '¿Se le informo el resultado del examen?');
INSERT INTO tc_Pregunta (id, texto) VALUES (68, 'Indique la fecha en que se le informo el resultado del examen');
INSERT INTO tc_Pregunta (id, texto) VALUES (69, 'Indique la fecha en que se le realizo la consulta de control siguiente al informe de resultados del examen');
INSERT INTO tc_Pregunta (id, texto) VALUES (70, '¿Se realizo una toma de muestra para biopsia?');
INSERT INTO tc_Pregunta (id, texto) VALUES (71, '¿Por que no se realizo la toma de muestra?');
INSERT INTO tc_Pregunta (id, texto) VALUES (72, 'Otro motivo');
INSERT INTO tc_Pregunta (id, texto) VALUES (73, '¿Se le informo el resultado del procedimiento?');
INSERT INTO tc_Pregunta (id, texto) VALUES (74, 'Indique la fecha en que se le informo el resultado del procedimiento');
INSERT INTO tc_Pregunta (id, texto) VALUES (75, 'Indique la fecha en que se le realizo la consulta de control posterior al informe de resultados del examen');
INSERT INTO tc_Pregunta (id, texto) VALUES (76, '¿Donde se realizo la lectura del examen?');
INSERT INTO tc_Pregunta (id, texto) VALUES (77, 'Indique la fecha de envio del examen para lectura');
INSERT INTO tc_Pregunta (id, texto) VALUES (78, 'Indique la fecha de devolucion del resultado del examen');
INSERT INTO tc_Pregunta (id, texto) VALUES (79, '¿Donde se realizo el informe del examen?');
INSERT INTO tc_Pregunta (id, texto) VALUES (80, '¿Que tipo de estudios moleculares especificos?');
INSERT INTO tc_Pregunta (id, texto) VALUES (81, 'Otro estudio');
INSERT INTO tc_Pregunta (id, texto) VALUES (82, 'Indique la fecha en que se le realizo la prestacion siguiente al informe de resultados del procedimiento');
INSERT INTO tc_Pregunta (id, texto) VALUES (83, 'Indique que profesional lo atendio');
INSERT INTO tc_Pregunta (id, texto) VALUES (84, '¿Cual otro profesional?');
INSERT INTO tc_Pregunta (id, texto) VALUES (85, '¿Que intencion de radioterapia se le indico?');
INSERT INTO tc_Pregunta (id, texto) VALUES (86, '¿Existe informacion disponible con respecto a quimioterapia?');
INSERT INTO tc_Pregunta (id, texto) VALUES (87, 'Carcinoma de celulas pequenasEnfermedad extendida metastasica');
INSERT INTO tc_Pregunta (id, texto) VALUES (88, 'Enfermedad limitada o localizada concominante con o sin radioterapia');
INSERT INTO tc_Pregunta (id, texto) VALUES (89, 'Carcinoma de celulas no pequenas');
INSERT INTO tc_Pregunta (id, texto) VALUES (90, 'Seguimiento segundo ano');
INSERT INTO tc_Pregunta (id, texto) VALUES (91, 'Seguimiento tercer ano');
INSERT INTO tc_Pregunta (id, texto) VALUES (92, 'Seguimiento cuarto ano');
INSERT INTO tc_Pregunta (id, texto) VALUES (93, 'Seguimiento quinto ano');
INSERT INTO tc_Pregunta (id, texto) VALUES (94, 'Indique la fecha de inicio de la terapia');
INSERT INTO tc_Pregunta (id, texto) VALUES (95, '¿Cual otro especialista?');
INSERT INTO tc_Pregunta (id, texto) VALUES (96, 'Indique que medico lo atendio');
INSERT INTO tc_Pregunta (id, texto) VALUES (97, '¿Cual otro medico?');
INSERT INTO tc_Pregunta (id, texto) VALUES (98, 'Quimioterapia adyuvante cancer de colon');
INSERT INTO tc_Pregunta (id, texto) VALUES (99, 'Seguimiento cancer de colon, anos 3, 4 y 5');